### PR TITLE
Make VCR ignore oauth-related requests

### PR DESCRIPTION
**Pull request by andylolz**
Trying this again (see #13). but from the same repo.

Refs #12.

### CODE REVIEW

**Comment by pezholio** [comment]
Oooh, fail, but better fail this time :)

**Comment by andylolz** [comment]
YES! You’re right – better fail :) Okay, ace. Thanks!

**Comment by pezholio** [comment]
Annoying how encrypted environment vars don't work on forks. I guess it's unavoidable though really.

**Comment by andylolz** [comment]
Oh… I massively failed at using `hub`. This PR is still from my fork!

**Pull request closed without merging**
