### PR TITLE
Make VCR ignore oauth-related requests

### PR DESCRIPTION
**Pull request by andylolz**
I’m not sure this is quite right, though it does seem to fix the issue (locally, at least).
WDYT, @Floppy?

Refs #12.

### CODE REVIEW

**Comment by pezholio** [comment]
I think this might work, but you'll need to encrypt the real values in the .travis.yml for the tests to pass in Travis (using `travis encrypt FOO=bar` or whatever). Seems legit though. I think it makes sense to authorise each time, rather than mocking it out.

**Comment by andylolz** [comment]
gah. I added encrypted versions of `GAPPS_CLIENT_ID`, `GAPPS_CLIENT_SECRET`, `GAPPS_ACCESS_TOKEN` and `GAPPS_REFRESH_TOKEN` but still getting an error.

**Comment by andylolz** [comment]
I guess I’m doing something wrong when creating the travis encrypted variables. From the repo directory, I’m running e.g.:

```
travis encrypt "GAPPS_CLIENT_ID=top_secret_secret_goes_here" --add
```

@pezholio if that’s obviously wrong, let me know! Otherwise I’m going to abandon this branch because I am well stuck.

**Comment by andylolz** [comment]
Oh right, yeah – I guess it’s because it’s a PR from a fork?

**Comment by pezholio** [comment]
Oh! Of course!

**Comment by pezholio** [comment]
I'll add you as a contributor so you can try creating a branch in this repo

**Comment by andylolz** [comment]
Ace – thanks! Closing this one…

**Pull request closed without merging**
